# Netlify configuration for ABS Memecoin website
# Optimized for TokenSOLver integration and trojan horse strategy

[build]
  # No build command needed for static site
  publish = "."
  
[build.environment]
  # Environment variables for build process
  NODE_VERSION = "18"

# Redirect rules for API proxy and clean URLs
[[redirects]]
  from = "/api/*"
  to = "https://solana-universal-analytics.onrender.com/api/:splat"
  status = 200
  force = true
 
[[redirects]]
  from = "/*"
  to = "https://:host/:splat"
  status = 301
  force = true
  conditions = { Protocol = "http" }
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' plausible.io; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://solana-universal-analytics.onrender.com https://plausible.io; font-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-src 'self' https://dexscreener.com https://*.dexscreener.com https://pump.fun https://*.pump.fun;"
    Strict-Transport-Security = "max-age=31536000"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Preload critical resources
[[headers]]
  for = "/index.html"
  [headers.values]
    Link = "</css/main.css>; rel=preload; as=style, </css/tokensolve.css>; rel=preload; as=style, </js/tokensolve.js>; rel=preload; as=script, </js/main.js>; rel=preload; as=script"

# Functions (if using Netlify Functions)
[functions]
  directory = "functions"

# Form handling (if needed)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
